In [159]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [161]:
df1 = pd.read_csv('train.csv')
df1.shape

(891, 12)

In [163]:
df2 = pd.read_csv('test.csv')
df2.shape

(418, 11)

In [165]:
df = pd.concat([df1,df2])

In [15]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [21]:
df.shape

(1309, 12)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1309 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     891 non-null    float64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   object
 4   Sex          1309 non-null   object
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    object
 11  Embarked     1307 non-null   object
dtypes: float64(3), int64(4), object(5)
memory usage: 132.9+ KB

In [167]:
df.isnull().sum()

PassengerId       0
Survived        418
Pclass            0
Name              0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
dtype: int64

In [27]:
df.dtypes

PassengerId      int64
Survived       float64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [169]:
df.drop('Name',axis=1)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1.0,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,female,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,NaN,3,male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,NaN,1,female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,NaN,3,male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,NaN,3,male,NaN,0,0,359309,8.0500,NaN,S
417,1309,NaN,3,male,NaN,1,1,2668,22.3583,NaN,C

In [171]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [173]:
df.isnull().sum()

PassengerId       0
Survived        418
Pclass            0
Name              0
Sex               0
Age               0
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
dtype: int64

In [175]:
df = df.drop('Cabin',axis=1)

In [177]:
df = df.drop('Ticket',axis=1)

In [179]:
df = df.drop('Name',axis=1)

In [181]:
df = df.drop('PassengerId',axis=1)

In [59]:
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [183]:
df['Sex'] = df['Sex'].map({'male':0,'female':1})

In [205]:
df['Embarked'].unique()

array([ 1.,  2.,  3., nan])

In [207]:
df['Embarked'] = df['Embarked'].map({'S':1,'C':2,'Q':3,'nan':4})

In [209]:
df

     Survived  Pclass  Sex        Age  SibSp  Parch     Fare  Embarked
0         0.0       3    0  22.000000      1      0   7.2500       NaN
1         1.0       1    1  38.000000      1      0  71.2833       NaN
2         1.0       3    1  26.000000      0      0   7.9250       NaN
3         1.0       1    1  35.000000      1      0  53.1000       NaN
4         0.0       3    0  35.000000      0      0   8.0500       NaN
..        ...     ...  ...        ...    ...    ...      ...       ...
886       0.0       2    0  27.000000      0      0  13.0000       NaN
887       1.0       1    1  19.000000      0      0  30.0000       NaN
888       0.0       3    1  29.881138      1      2  23.4500       NaN
889       1.0       1    0  26.000000      0      0  30.0000       NaN
890       0.0       3    0  32.000000      0      0   7.7500       NaN

[891 rows x 8 columns]

In [189]:
df.isnull().sum()

Survived    418
Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          1
Embarked      2
dtype: int64

In [191]:
df['Fare'] = df['Fare'].fillna(df['Fare'].mode()[0])

In [193]:
df['Fare'].mode()

0    8.05
Name: Fare, dtype: float64

In [195]:
df['Survived'].mean()

0.3838383838383838

In [197]:
df.dropna(subset=['Survived'], inplace=True)

In [199]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    2
dtype: int64

In [203]:
df[df['Embarked'] == '']

Empty DataFrame
Columns: [Survived, Pclass, Sex, Age, SibSp, Parch, Fare, Embarked]
Index: []

In [147]:
df.shape

(891, 8)

In [149]:
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       0.0       3    0  22.0      1      0   7.2500       NaN
1       1.0       1    1  38.0      1      0  71.2833       NaN
2       1.0       3    1  26.0      0      0   7.9250       NaN
3       1.0       1    1  35.0      1      0  53.1000       NaN
4       0.0       3    0  35.0      0      0   8.0500       NaN

In [211]:
df = df.drop('Embarked',axis=1)

In [213]:
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare
0       0.0       3    0  22.0      1      0   7.2500
1       1.0       1    1  38.0      1      0  71.2833
2       1.0       3    1  26.0      0      0   7.9250
3       1.0       1    1  35.0      1      0  53.1000
4       0.0       3    0  35.0      0      0   8.0500

In [215]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
dtype: int64

In [219]:
X = df.drop('Survived',axis=1)
y = df['Survived']

In [221]:
X

     Pclass  Sex        Age  SibSp  Parch     Fare
0         3    0  22.000000      1      0   7.2500
1         1    1  38.000000      1      0  71.2833
2         3    1  26.000000      0      0   7.9250
3         1    1  35.000000      1      0  53.1000
4         3    0  35.000000      0      0   8.0500
..      ...  ...        ...    ...    ...      ...
886       2    0  27.000000      0      0  13.0000
887       1    1  19.000000      0      0  30.0000
888       3    1  29.881138      1      2  23.4500
889       1    0  26.000000      0      0  30.0000
890       3    0  32.000000      0      0   7.7500

[891 rows x 6 columns]

In [223]:
y

0      0.0
1      1.0
2      1.0
3      1.0
4      0.0
      ...
886    0.0
887    1.0
888    0.0
889    1.0
890    0.0
Name: Survived, Length: 891, dtype: float64

In [225]:
df.dtypes

Survived    float64
Pclass        int64
Sex           int64
Age         float64
SibSp         int64
Parch         int64
Fare        float64
dtype: object

In [227]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [229]:
print(X.shape,X_train.shape,X_test.shape)

(891, 6) (712, 6) (179, 6)

In [231]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train,y_train)

LogisticRegression()

In [233]:
X_train_pred = model.predict(X_train)

In [237]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(X_train_pred,y_train)

print('The accuracy is ',acc)

The accuracy is The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.
 0.8146067415730337

In [239]:
X_test_pred = model.predict(X_test)

In [243]:
acc = accuracy_score(X_test_pred,y_test)

print('The accuracy is ',acc*100)

The accuracy is  77.6536312849162

In [271]:
data = np.asarray(['1','0','16','1.4','2','45.5'],dtype=float).reshape(1,-1)

In [273]:
res = model.predict(data)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [275]:
if res == 0:
    print('Dead')
else:
    print('Alive')

Dead

In [277]:
import pickle

In [283]:
pickle.dump(model,open('model.pkl','wb'))

In [285]:
pickled_model = pickle.load(open('model.pkl','rb'))

In [293]:
pickled_model.predict(data)[0]

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

0.0